#!/usr/bin/env bash
# config.sh — プロジェクト設定のロード
#
# カレントディレクトリ（またはその親）にある .project-flow.conf を読み込む

set -euo pipefail

PROJECT_FLOW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# .project-flow.conf を探す（カレントディレクトリから上に辿る）
find_config() {
  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    if [[ -f "$dir/.project-flow.conf" ]]; then
      echo "$dir/.project-flow.conf"
      return
    fi
    dir="$(dirname "$dir")"
  done
  echo ""
}

# 設定を読み込む
load_project_config() {
  local conf_file
  conf_file=$(find_config)

  if [[ -z "$conf_file" ]]; then
    echo "ERROR: .project-flow.conf が見つかりません。先に project-flow setup を実行してください。" >&2
    return 1
  fi

  PROJECT_ROOT="$(dirname "$conf_file")"
  PROJECT_CONF_FILE="$conf_file"

  # デフォルト値
  REPO=""
  OWNER=""
  REPO_NAME=""
  PROJECT_NUMBER=""
  STATUS_FIELD_NAME="Status"
  STATUS_BACKLOG="Backlog"
  STATUS_ANALYSIS="Analysis"
  STATUS_DEV="Dev"
  STATUS_REVIEW="Review"
  STATUS_QA="QA"
  STATUS_ACCEPT="Accept"
  STATUS_DONE="Done"
  POLL_INTERVAL=60
  LOCAL_REPO_PATH=""

  # 設定ファイルを読み込み
  source "$conf_file"

  # LOCAL_REPO_PATH のデフォルトはプロジェクトルート
  if [[ -z "$LOCAL_REPO_PATH" ]]; then
    LOCAL_REPO_PATH="$PROJECT_ROOT"
  fi

  # ログ・プロンプトディレクトリ
  local safe_name="${OWNER}__${REPO_NAME}"
  LOG_DIR="${PROJECT_ROOT}/.project-flow-logs"
  PROMPTS_DIR="${PROJECT_FLOW_DIR}/prompts"
  TMUX_SESSION="pf-${safe_name}"

  mkdir -p "$LOG_DIR"
}

# 設定ファイルを作成
save_project_config() {
  cat > "$PROJECT_CONF_FILE" << EOF
# project-flow config
# Generated by: project-flow setup
REPO="${REPO}"
OWNER="${OWNER}"
REPO_NAME="${REPO_NAME}"
PROJECT_NUMBER="${PROJECT_NUMBER}"
STATUS_FIELD_NAME="${STATUS_FIELD_NAME}"
STATUS_BACKLOG="${STATUS_BACKLOG}"
STATUS_ANALYSIS="${STATUS_ANALYSIS}"
STATUS_DEV="${STATUS_DEV}"
STATUS_REVIEW="${STATUS_REVIEW}"
STATUS_QA="${STATUS_QA}"
STATUS_ACCEPT="${STATUS_ACCEPT}"
STATUS_DONE="${STATUS_DONE}"
POLL_INTERVAL="${POLL_INTERVAL}"
LOCAL_REPO_PATH=""
EOF
}
