#!/usr/bin/env bash
# config.sh — Load project configuration
#
# Reads .project-flow.conf from current directory (or parent directories)

set -euo pipefail

PROJECT_FLOW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Find .project-flow.conf by traversing up from PWD
find_config() {
  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    if [[ -f "$dir/.project-flow.conf" ]]; then
      echo "$dir/.project-flow.conf"
      return
    fi
    dir="$(dirname "$dir")"
  done
  echo ""
}

# Load configuration
load_project_config() {
  local conf_file
  conf_file=$(find_config)

  if [[ -z "$conf_file" ]]; then
    echo "ERROR: .project-flow.conf not found. Run project-flow setup first." >&2
    return 1
  fi

  PROJECT_ROOT="$(dirname "$conf_file")"
  PROJECT_CONF_FILE="$conf_file"

  # Defaults
  REPO=""
  OWNER=""
  REPO_NAME=""
  PROJECT_NUMBER=""
  STATUS_FIELD_NAME="Status"
  STATUS_BACKLOG="Backlog"
  STATUS_ANALYSIS="Analysis"
  STATUS_DEV="Dev"
  STATUS_REVIEW="Review"
  STATUS_QA="QA"
  STATUS_ACCEPT="Accept"
  STATUS_DONE="Done"
  POLL_INTERVAL=60
  LOCAL_REPO_PATH=""

  # Source config file
  source "$conf_file"

  # Default LOCAL_REPO_PATH to project root
  if [[ -z "$LOCAL_REPO_PATH" ]]; then
    LOCAL_REPO_PATH="$PROJECT_ROOT"
  fi

  # Derived paths
  local safe_name="${OWNER}__${REPO_NAME}"
  LOG_DIR="${PROJECT_ROOT}/.project-flow-logs"
  PROMPTS_DIR="${PROJECT_FLOW_DIR}/prompts"
  TMUX_SESSION="pf-${safe_name}"

  mkdir -p "$LOG_DIR"
}

# Write configuration file
save_project_config() {
  cat > "$PROJECT_CONF_FILE" << EOF
# project-flow config
# Generated by: project-flow setup
REPO="${REPO}"
OWNER="${OWNER}"
REPO_NAME="${REPO_NAME}"
PROJECT_NUMBER="${PROJECT_NUMBER}"
STATUS_FIELD_NAME="${STATUS_FIELD_NAME}"
STATUS_BACKLOG="${STATUS_BACKLOG}"
STATUS_ANALYSIS="${STATUS_ANALYSIS}"
STATUS_DEV="${STATUS_DEV}"
STATUS_REVIEW="${STATUS_REVIEW}"
STATUS_QA="${STATUS_QA}"
STATUS_ACCEPT="${STATUS_ACCEPT}"
STATUS_DONE="${STATUS_DONE}"
POLL_INTERVAL="${POLL_INTERVAL}"
LOCAL_REPO_PATH=""
EOF
}
